### PR TITLE
len() function for COO objects

### PR DESCRIPTION
**Pull request by nils-werner**
Quite trivial really, implements the `len()` operation following NumPy's convention of

    len(array) == array.shape[0]

### CODE REVIEW

**Comment by nils-werner** [comment]
Added them

**Comment by hameerabbasi** [comment]
Well, this looks good. Let me know if you're finished working on it, and I'll review and merge (don't want to be too fast this time).

**Comment by nils-werner** [comment]
This is ready to be merged.

**Comment by mrocklin** [comment]
Agreed.

**Comment by mrocklin** [comment]
Thanks @nils-werner !

**Comment by nils-werner** [comment]
One unexpected sideeffect of this:

    numpy.array(cooarr)

now magically works!

    x = sparse.random((20, 30))
    np.allclose(x.todense(), np.array(x))    # True

**Comment by hameerabbasi** [comment]
I'm going to assume it's really slow. Do we have any benchmarks for this?

**Comment by nils-werner** [comment]
Yes, it's very very slow.

If I understand it correctly, `numpy.array(x)` looks for `buffer` and `__array_interface__` when creating an array from an object. If it doesn't find one it simply iterates over it.

What if we implement `__array_interface__` that calls `self.todense()`?

    @property
    def __array_interface__(self):
        return {
            'shape': self.shape,
            'data': self.todense(),
            'typestr': self.dtype.str,
        }

Before

    x = sparse.random((20, 30, 20))

    %timeit numpy.array(x)
    # 1.48 s ± 25.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    %timeit x.todense()
    # 11.6 µs ± 40.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

After

    %timeit numpy.array(x)
    # 23 µs ± 392 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

**Comment by hameerabbasi** [comment]
A pull request would be welcome. Also, your data is too small. Maybe it's just the overhear.

**Pull request merged**
